global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-server'
    static_configs:
      - targets: ['api-server:8080']
  - job_name: 'manager'
    static_configs:
      - targets: ['manager:9090']
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:9797']