apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: supernova
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus-config.yml"
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
          ports:
            - containerPort: 9090
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
