apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: supernova
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: "8080"
  type: LoadBalancer