apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: supernova
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              value: "postgres"
          resources:
            limits:
              cpu: 20000m
              memory: 20000Mi
              tke.cloud.tencent.com/eni-ip: "1"
            requests:
              cpu: 18000m
              memory: 18000Mi
              tke.cloud.tencent.com/eni-ip: "1"
          volumeMounts:
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
            - name: postgres-pv-docker-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init-script
        - name: postgres-pv-docker-volume
          persistentVolumeClaim:
            claimName: postgres-pvc-docker-volume