apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: supernova
spec:
  selector:
    app: worker
  ports:
    - name: "50051"
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: "metrics"
      protocol: TCP
      port: 9797
      targetPort: 9797
  type: ClusterIP
  