apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
data:
  pgbouncer.ini: |
    [databases]
    postgres = host=postgres port=5432 dbname=postgres

    [pgbouncer]
    listen_port = 5432
    listen_addr = *
    auth_type = plain
    auth_file = /etc/pgbouncer/userlist.txt
    logfile = /var/log/pgbouncer/pgbouncer.log
    pidfile = /var/run/pgbouncer/pgbouncer.pid
    max_client_conn = 1900
    default_pool_size = 1800