apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: supernova
data:
  DB_USER: "postgres"
  DB_PASSWORD: "970409"
  DB_HOST: "postgres"
  DB_NAME: "postgres"
  POOL_MODE: "session"
  ADMIN_USERS: "postgres"
  AUTH_TYPE: "plain"
  MAX_CLIENT_CONN: "5000"
  DEFAULT_POOL_SIZE: "5000"
  RESERVE_POOL_SIZE: "5000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: supernova
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pgbouncer-config

---

apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: supernova
spec:
  selector:
    app: pgbouncer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP