apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: supernova
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: {{.Values.apiServer.service.port}}
      targetPort: {{.Values.apiServer.service.port}}
      name: "8080"
  type: {{.Values.apiServer.service.type}}