apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  labels:
    app: api-server
  namespace: supernova
spec:
  replicas: {{.Values.apiServer.replicaCount}}
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: "{{.Values.apiServer.image.repository}}:{{.Values.apiServer.image.tag}}"
          imagePullPolicy: {{.Values.apiServer.image.pullPolicy}}
          command: {{.Values.apiServer.command}}
          ports:
            - containerPort: {{.Values.apiServer.port}}