apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: supernova
spec:
  selector:
    app: manager
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: "grpc"
      port: 50051
      targetPort: 50051
      protocol: TCP
  type: ClusterIP
  