apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-docker-volume
  namespace: supernova
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi