apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: supernova
  name: endpoints-reader
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-endpoints
  namespace: supernova
subjects:
  - kind: ServiceAccount
    name: default
    namespace: supernova
roleRef:
  kind: Role
  name: endpoints-reader
  apiGroup: rbac.authorization.k8s.io

