apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: supernova
  name: lease-access-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lease-access-rolebinding
  namespace: supernova
subjects:
  - kind: ServiceAccount
    name: default
    namespace: supernova
roleRef:
  kind: Role
  name: lease-access-role
  apiGroup: rbac.authorization.k8s.io