apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-docker-volume
  namespace: supernova
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/grafana-data