apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv0
  namespace: supernova
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/c/Users/robingowang/Desktop/grafana/data