apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-docker-volume
  namespace: supernova
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-data/
  