apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-10g
  namespace: supernova
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/c/Users/robingowang/Desktop/postgres/data
  